name: nlp_task_mia_env
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python=3.10
  - numpy=1.21.6
  - pandas=1.3.5
  - matplotlib=3.8.4
  - seaborn=0.11.2
  - scikit-learn=1.0.2
  - tensorflow=2.10.0
  - keras=2.10.0
  - nltk=3.7
  - tensorflow-hub=0.12.0
  - jupyterlab=3.4.4
  - notebook=6.4.8
  - scikit-image=0.19.3
  - opencv=4.5.3
  - pytorch=1.12.1
  - privacy-preserving-models=0.1.0  # For applying privacy preservation
  - random-forest=0.4.0  # For RandomForest classifier
  - loguru-0.7.3
   - pydantic=2.7
  - pydantic-settings=2.0
  - python-dotenv
  - ipykernel
  - pip:
      - mia= 0.1.2  
